#!/usr/bin/env bash
# download-fonts.sh — self-host Google Fonts for CSP compliance
#
# Downloads DM Serif Display and DM Sans woff2 files and generates
# a local fonts.css file. Run once from the repo root:
#
#   bash scripts/download-fonts.sh
#
# Output:
#   app/fonts/*.woff2      — font files served as static assets
#   app/fonts.css          — @font-face declarations (replaces Google Fonts import)

set -euo pipefail

FONTS_DIR="app/fonts"
CSS_OUT="app/fonts.css"
GOOGLE_FONTS_URL="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;1,9..40,300&display=swap"

# Use a modern Chrome UA so Google returns woff2 (not woff/ttf for old browsers)
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"

echo "→ Creating $FONTS_DIR/"
mkdir -p "$FONTS_DIR"

echo "→ Fetching Google Fonts CSS..."
CSS=$(curl -fsSL --user-agent "$UA" "$GOOGLE_FONTS_URL")

if [ -z "$CSS" ]; then
  echo "ERROR: empty response from Google Fonts — check network access" >&2
  exit 1
fi

echo "→ Parsing font URLs..."
# Extract all woff2 URLs
URLS=$(echo "$CSS" | grep -oE 'https://fonts\.gstatic\.com/[^)]+\.woff2')
COUNT=$(echo "$URLS" | wc -l | tr -d ' ')
echo "  Found $COUNT font files"

# Download each woff2, name it by a hash of the URL to avoid collisions
declare -A URL_TO_FILE
while IFS= read -r url; do
  # Derive a stable filename from the URL path
  filename=$(echo "$url" | sed 's|https://fonts.gstatic.com/||' | tr '/' '-')
  dest="$FONTS_DIR/$filename"
  if [ -f "$dest" ]; then
    echo "  skip  $filename (already exists)"
  else
    echo "  fetch $filename"
    curl -fsSL -o "$dest" "$url"
  fi
  URL_TO_FILE["$url"]="$filename"
done <<< "$URLS"

echo "→ Generating $CSS_OUT..."
# Replace each google fonts URL in the CSS with the local path, strip @import line
LOCAL_CSS="$CSS"

# Remove the @import line (not needed — we ARE the stylesheet now)
LOCAL_CSS=$(echo "$LOCAL_CSS" | grep -v '@import')

# Rewrite each woff2 URL to a local path
for url in "${!URL_TO_FILE[@]}"; do
  filename="${URL_TO_FILE[$url]}"
  LOCAL_CSS="${LOCAL_CSS//$url/\/fonts\/$filename}"
done

# Write out
cat > "$CSS_OUT" <<EOF
/* Auto-generated by scripts/download-fonts.sh — do not edit */
/* Self-hosted DM Serif Display + DM Sans (replaces Google Fonts import) */
$LOCAL_CSS
EOF

echo "→ Done."
echo ""
echo "Next steps:"
echo "  1. In index.html, replace:"
echo "       <style>@import url('https://fonts.googleapis.com/...')</style>"
echo "     with:"
echo "       <link rel=\"stylesheet\" href=\"/fonts.css\">"
echo "  2. Redeploy. No nginx CSP changes needed."
